//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGames.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardGames.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGDb.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string TopListsAbstract {
            get {
                return ResourceManager.GetString("TopListsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TopListsAll {
            get {
                return ResourceManager.GetString("TopListsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s.
        /// </summary>
        public static string TopListsChildrens {
            get {
                return ResourceManager.GetString("TopListsChildrens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable.
        /// </summary>
        public static string TopListsCustomizable {
            get {
                return ResourceManager.GetString("TopListsCustomizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string TopListsFamily {
            get {
                return ResourceManager.GetString("TopListsFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string TopListsParty {
            get {
                return ResourceManager.GetString("TopListsParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string TopListsStrategy {
            get {
                return ResourceManager.GetString("TopListsStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thematic.
        /// </summary>
        public static string TopListsThematic {
            get {
                return ResourceManager.GetString("TopListsThematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War.
        /// </summary>
        public static string TopListsWar {
            get {
                return ResourceManager.GetString("TopListsWar", resourceCulture);
            }
        }
    }
}
